server:
  port: 80
  context-path: /

spring:
  freemarker:
    template-loader-path: classpath:/templates
    charset: utf-8
    cache: false #关闭缓存及时刷新
    check-template-location: true
    content-type: text/html
    suffix: .ftl
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
